import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/lib/auth";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartQuiz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`dark antialiased ${geistMono.className} min-h-svh flex flex-col`}
      >
        <Header session={session} />
        <main className="flex-grow flex flex-col items-center overflow-x-hidden">
          {children}
        </main>
        <Footer />
        <Toaster richColors closeButton duration={1000} />
      </body>
    </html>
  );
}
