import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartQuiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dark antialiased ${geistMono.className} h-svh flex flex-col p-4 mx-auto`}
      >
        <Header />
        <main className="flex-grow flex flex-col justify-center items-center relative">
          {children}
        </main>
        <Toaster richColors closeButton duration={200} />
        <Footer />
      </body>
    </html>
  );
}
